### ISSUE TITLE
How to get the accurate data?

### ISSUE THREAD

**Issue by suntea233** [WoodScene/LDST#3]
I download the dataset you mentioned in README.md, but how can i get the train data for MultiWOZ 2.2?

**Comment by WoodScene** [comment]
I appreciate your reminder and apologize for the inconvenience. Due to some security issues on our servers that temporarily make it impossible to link, we will release the MultiWOZ 2.2 preprocessing code as soon as possible.
If you need the code urgently, you can make minor modifications to either 'data_prepare_few-shot_multiwoz20.py' or 'data_prepare_few-shot_multiwoz24.py', as they are similar to MultiWOZ 2.2.

**Comment by suntea233** [comment]
Thank u for your answering!

**Comment by vikotse** [comment]
> I appreciate your reminder and apologize for the inconvenience. Due to some security issues on our servers that temporarily make it impossible to link, we will release the MultiWOZ 2.2 preprocessing code as soon as possible. If you need the code urgently, you can make minor modifications to either 'data_prepare_few-shot_multiwoz20.py' or 'data_prepare_few-shot_multiwoz24.py', as they are similar to MultiWOZ 2.2.

@suntea233 Hello, may I ask when the MultiWOZ 2.2 preprocessing code will be released?
